##### 1. R 다운로드 및 설치

1.  https://cran.r-project.org 
      ... Download R for Windows
      ... install R for the first time
      ... Download R 3.6.? for windows
   
2. RStudio 다운로드 및 설치
   
      ... http://www.rstudio.com > Download RStudio > Free Download
      
3. Anconda에서 R 설치
   
      ... Anaconda Prompt창에서 : conda install -c r r-essentials
  
  
##### 2. R이란?

1. 데이터분석을 위한 언어 및 패키지
 - SPSS
 - SAS
 - Python
 - R
 - WEKA : 자바기반의 데이터 마이닝 소프웨어 

2. R

 - 통계계산과 그래프작성에 특화된 언어
 - 데이터분석을 위한 통계 및 그래픽을 지원하는 Free Software
 - Google, Facebook등에서 R을 주된 분석 플랫폼으로 사용하고 있음
 - 다양한 추가기능을 별도의 패키지형태로 제공
 - Histroy
   * 1995년 뉴질랜트 오클랜드대학의 Ross Ihaka 와 Robert Gentlemane이 개발
   * 2000년 R1.0공개(개발자 두명의 이름이 모두 R로 시작해서 R로 명명)
   * 2002년 R Foundation설립
   
##### 3. R의 기본문법

1. 도움말
 * help(log)
 * ?log
 * 예약어에 대한 도움말을 보고 싶을 경우에는 따옴표로 묶는다. 예를 들어 help("for")
 * 사용예제를 보고싶을 경우 example()함수를 사용. 예를 들어 lm함수의 예제일 경우 example(lm)
 
2. 주석 : 한줄주석은 #로 시작

3. 산술연산자

   +, -, *, /(실수나눗셈), `%/%(정수나눗셈)`, %%(나머지), **(거듭제곱)
   
4. R에서 지원하는 함수

   sin(x)
   log(x)
   sqrt(x) : 제곱근
   abs(x) 
   trunc(x) : 소숫점이하 버림
   round(x, 소수자리수) : 소수자리수기준 반올림
   runif(n) : 0~1사이의 난수 n개생성 
   
##### 4. 변수

R에서서 사용하는 데이터셋의 형태는 `벡터 Vector`이다. R에서 사용하는 가장 기본적인 데이터셋의 형태는 Vector이고 `하나 이상의 숫자, 문자등의 집합을 벡터(vector)`이라고 한다. 
벡터는 행과 열로 가지는 표형식으로 확장한 것이 `행렬 Matrix`이다. 또한, 벡터의 집합을 원소로 가지는 데이터의 형태를 `리스트 List`라 하고, 리스트에 포함된 벡터의 길이가 같을 때 이 자룡의 형태를 `데이터프레임 Data Frame`으로 취급할 수 있다.

1. 물리학용어
 * scalar : 크기(값)만 가지고 있는 물리량
 * vector : 크기(값)와 방향을 모두 가지고 있는 물리량
2. R에서의 vector은 `값들의 집합`이다.
>* R에서는 scalar인 하나의 숫자도 하나의 원소를 갖는 vector로 취급한다.
>* vector는 R에서 `최소단위`이다.
>* vector의 `index는 1부터 시작한다`(주의: 0이 아니라 1이다.)
>* vector에서 결측값(누락된 값)은 `NA Not Avaliable`을 사용한다.

##### 5. 패키지관련

>* 인스톨된 패키지를 출력 : `installed.packages()`
* 패키지를 사용(로드) : `library(패키지명)`
* 패키지 설치 : `install.packages('패키지명')`
* 패키지 업데이트 : `update.packages()`
* 패키지 버전확인 : `installed.packages()[,c("Package", "Version")]`
* 자주사용하는 패키지
>>* rgl : OpenGL사용해서 3차원 그래프
>>* ggplot2 : 데이터시각화 패키지
>>* ggthemes : ggplot2에 테마적용
>>* data.table : data.frame의 기능을 확장
>>* devtools : R패키지의 개발을 쉽게 개발하는데 지원
>>* dplyr : 데이터의 조작을 빠르고 쉽게 지원
>>* plyr : 데이터의 추가, 연결, 분할하는 등의 기능 제공
>>* reshape2 : 데이터의 형태(크기)를 유연하게 재구성기능을 제공
>>* scales : 스케일관련 기능을 제공
>>* stringr : 문자열데이터를 간단하고 쉽게 조작하는 기능을 제공

##### 6. R관련 검색방법

* http://rseek.org
* http://cran.r-project.org/manuals.html

In [ ]:
installed.packages()[,c("Package", "Version")]

In [ ]:
update.packages()

In [6]:
# R에서 제공하는 기본데이터셋 목록보기
data()

##### 변수와 자료형

1. scalar : R의 벡터자료구조로서 `한개의 값만 갖는 벡터`이다.
2. vector : R은 실수, 복소수, 문자열, 논리값등의 기본 데이터를 하나씩 단독으로 사용하는 것이 아니라 `같은 종류의 데이터를 여러개 묶은 벡터형식`으로 다룬다. 

>벡터를 만드는 가장 간단한 방법은 `c()`함수를 이용하는 방법이다. 함수 c()의 인수값으로 벡터에 넣고 싶은 값들을 열거하면 목적하는 벡터를 만들 수 있다.

###### 1. R에서의 자료형

1. 숫자형 : 정수, 실수
2. 문자형 : 문자, 문자열
3. 논리형 : TRUE(T), FALSE(F)
4. 결측형 : NA or NaN

###### 2. 자료형확인

1. is.numerix() : 숫자여부
2. is.integer() : 정수여부
3. is.logical() 
4. is.double() : 실수여부
5. is.character() : 문자여부
6. is.data.frame() : df여부
7. is.na() : NA여부
8. is.complex() : 복소수여부
9. is.factor() : 범주형여부
10.is.nan() : NaN여부

###### 3. 자료형변환

1. as.numeric()
2. as.integer()
3. as.logical()
4. as.double()
5. as.complex()
6. as.character()
7. as.data.frame()
8. as.factor()
9. as.list()
10. as.vector()
11. as.array()
12. as.Date()

In [7]:
# 변수
a <- 125
a
print(a)
b <- 100
print(b)
a+b
print(a+b)

a <- "A"
a
print(a+b) # 파이썬과 동일하게 에러발생

[1] 125

[1] 125
[1] 100


[1] 225

[1] 225


[1] "A"

ERROR: Error in a + b: 이항연산자에 수치가 아닌 인수입니다


In [8]:
# 벡터만들기
v <- c(1,2,3)
v
is.vector(v)

# 벡터의 길이
length(v)

is.numeric(v[1])

v1 <- c(1,2.5,3,'A')
is.vector(v1)
is.numeric(v1[1])

# 예에서 볼 수 있드시 벡터의 인덱스는 1부터시작한다.
# 벡터의 원소에 숫자와 문자가 함께 포함이 되면 벡터의 모든 원소들은 문자(character)로
# 변환됨에 주의하여야 한다.
# 특정의 변수가 벡터인지 여부를 확인하려면 is.vector()함수를 사용하며 벡터의 크기를 
# 알려면 length()함수를 사용한다.

# is.vector()함수의 결과가 TRUE이면 벡터임을 FALSE이면 다른 형태의 자료형임을 알려준다.

[1] 1 2 3

[1] TRUE

[1] 3

[1] TRUE

[1] TRUE

[1] FALSE

In [9]:
# 연속된 값을 가진 벡터 생성하기
1:5 # 1~5까지 1씩증가하는 벡터
5:-5 # 5~-5까지 1씩감소하는 벡터

[1] 1 2 3 4 5

[1]  5  4  3  2  1  0 -1 -2 -3 -4 -5

##### 기본함수

In [10]:
# 1. rep()함수 :
rep(1:3, length=10) # 길이가 10개인 벡터를 생성하는데 1~3까지를 반복
rep(1:3, times=10) # 1~3까지 10번반복

[1] 1 2 3 1 2 3 1 2 3 1

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [11]:
# 2. seq()
seq(1,10) # 1~10까지 연속된 벡터생성
seq(1,10, length=7) # 1~10까지 7등분
seq(1,10, by=2) # 2씩증가

[1]  1  2  3  4  5  6  7  8  9 10

[1]  1.0  2.5  4.0  5.5  7.0  8.5 10.0

[1] 1 3 5 7 9

In [12]:
# 3. unique() : 중복된 값 제외
rep(1:3, length=10)
unique(rep(1:3, length=10))

[1] 1 2 3 1 2 3 1 2 3 1

[1] 1 2 3

In [13]:
# 4. numeric() : 0으로 채워진 벡터생성
numeric(10) # 0이 10개
example(numeric)
?numeric

[1] 0 0 0 0 0 0 0 0 0 0


numerc> as.numeric(c("-.1"," 2.7 ","B")) # (-0.1, 2.7, NA)  +  warning


Warning message in eval(ei, envir):
"강제형변환에 의해 생성된 NA 입니다"

[1] -0.1  2.7   NA

numerc> as.numeric(factor(5:10)) # not what you'd expect
[1] 1 2 3 4 5 6

numerc> f <- factor(1:5)

numerc> ## what you typically meant and want:
numerc> as.numeric(as.character(f))
[1] 1 2 3 4 5

numerc> ## the same, considerably (for long factors) more efficient:
numerc> as.numeric(levels(f))[f]
[1] 1 2 3 4 5


In [14]:
# 5. sequence() : 패턴을 가지는 벡터생성
sequence(c(3,6,9)) # 1:3, 1:6, 1:9

[1] 1 2 3 1 2 3 4 5 6 1 2 3 4 5 6 7 8 9

In [15]:
# 6. names() : 벡터의 원소에 이름을 부여
score <- c(90,85,70)
score
names(score)
names(score) <- c("홍길동", "홍길순", "홍길녀")
score
names(score)

[1] 90 85 70

NULL

홍길동 홍길순 홍길녀 
    90     85     70

[1] "홍길동" "홍길순" "홍길녀"

##### 벡터에서 원소값 접근하기

In [16]:
# 1. 벡터원소의 값 추출
d <- c(1,4,5,8,9)
d[1]
d[3]
d[5]

[1] 1

[1] 5

[1] 9

In [18]:
# 2. 벡터원소여러개의 값을 한번에 추출
d <- c(1,4,5,8,9)
d[1:3] # 1,4,5
d[c(1,3,5)] # 1,5,9
d[seq(1,5,2)] # 홀수원소 1,5,9
d[-2] # 1,5,8,9
# 3~5원소를 뺀 나머지원소의 값을 추출해 보세요!
d[c(3:5)] # 5,8,9
d[-c(3:5)] # 1,4

[1] 1 4 5

[1] 1 5 9

[1] 1 5 9

[1] 1 5 8 9

[1] 5 8 9

[1] 1 4

In [19]:
# 3. 벡터에서 이름으로 값을 추출하기
score
score["홍길동"] # 홍길동 90
score[c("홍길동", "홍길녀")] # 홍길동과 홍길녀만 추출

홍길동 홍길순 홍길녀 
    90     85     70

홍길동 
    90

홍길동 홍길녀 
    90     70

In [20]:
# 4. 벡터원소의 값을 수정
v1 <- c(1,5,7,8,9)
v1
v1[2] <- 3 # 두번째 원소의 값을 5에서 3으로 변경해 보기
v1

v1[c(1,5)] <- c(10,20) # 1,9를 각각 10과 20으로 변경해 보기
v1

[1] 1 5 7 8 9

[1] 1 3 7 8 9

[1] 10  3  7  8 20

###### 벡터의 연산

In [21]:
# 1. 기본연산
d <- c(1,3,4,7,8)
d*2
d-5
d*3+4

[1]  2  6  8 14 16

[1] -4 -2 -1  2  3

[1]  7 13 16 25 28

In [22]:
# 2. 원소의 갯수가 다른 경우의 연산
# 1) 여러개의 원소를 가진 벡터와 한개의 값을 벡터와의 연산
x <- -5:5
y <- 5
x*y
x+y
x/y
x-y
print("------------------------")

# 2) 서로 복수개의 원소를 가진 벡터의 연산
# 전제조건 : 원소의 갯수가 동일해야 한다.
z <- c(1,2)
x*z # 에러발생 : 두 객체의 길이가 서로 배수관계에 있지 않습니다
length(x)
z <- 1:11
z
x*z
x-z
x+z
x/z

[1] -25 -20 -15 -10  -5   0   5  10  15  20  25

[1]  0  1  2  3  4  5  6  7  8  9 10

[1] -1.0 -0.8 -0.6 -0.4 -0.2  0.0  0.2  0.4  0.6  0.8  1.0

[1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0

[1] "------------------------"


Warning message in x * z:
"두 객체의 길이가 서로 배수관계에 있지 않습니다"

[1] -5 -8 -3 -4 -1  0  1  4  3  8  5

[1] 11

[1]  1  2  3  4  5  6  7  8  9 10 11

[1] -5 -8 -9 -8 -5  0  7 16 27 40 55

[1] -6 -6 -6 -6 -6 -6 -6 -6 -6 -6 -6

[1] -4 -2  0  2  4  6  8 10 12 14 16

[1] -5.0000000 -2.0000000 -1.0000000 -0.5000000 -0.2000000  0.0000000
 [7]  0.1428571  0.2500000  0.3333333  0.4000000  0.4545455

In [23]:
# 3. 비교연산
x <- c(1,2,3,4,5)
x[2]
x[-2]
x[3] <- 4
x
x[x>2 & x<5] # 2보다 크고 5보다 작은 값을 출력해 보세요!

y <- c(2,1,3,4,5)
x == y

[1] 2

[1] 1 3 4 5

[1] 1 2 4 4 5

[1] 4 4

[1] FALSE FALSE FALSE  TRUE  TRUE

In [24]:
# 4. 벡터의 연산
c(1,2) + c(4,5) # 5, 7
c(1,2,3) + 1 # 2,3,4

[1] 5 7

[1] 2 3 4

In [25]:
# 5. 함수를 이용한 벡터자료의 일부를 수정하기
# replace(), append()
x <- c(2,4,6,9)
y <- replace(x, c(2,4), c(32, 34)) # 4->32, 9->34
y
w <- append(x, y) # x와 y를 합치기
w
z <- append(x, y, after=2) # x의 2번째 뒤에 y를 삽입하기
z

[1]  2 32  6 34

[1]  2  4  6  9  2 32  6 34

[1]  2  4  2 32  6 34  6  9

###### 벡터에 적용 가능한 함수

>* sum() : 벡터에 포함된 값들의 합
* mean() : 벡터에 포함된 값들의 평균
* median() : 벡터에 포함된 값들의 중앙값
* max(), min()
* var() : 벡터에 포함된 값들의 분산
* sd() : 표준편차
* sort() : 값들을 정렬(기본은 오름차순)
* range() : 벡터에 포함된 값들의 범위(최소값~최대값)
* length() : 벡터의 요소의 갯수

In [26]:
# 벡터적용함수 실습하기
d <- c(1,2,3,4,5,6,7,8,9,10)
sum(d)
sum(d*2)
length(d)
mean(d)
mean(d[1:5])
max(d[1:5])
max(d)
min(d)
sort(d)
sort(d, decreasing = F)
sort(d, decreasing = T)

v1 <- median(d)
v1
v2 <- sum(d) / length(d)
v2

[1] 55

[1] 110

[1] 10

[1] 5.5

[1] 3

[1] 5

[1] 10

[1] 1

[1]  1  2  3  4  5  6  7  8  9 10

[1]  1  2  3  4  5  6  7  8  9 10

[1] 10  9  8  7  6  5  4  3  2  1

[1] 5.5

[1] 5.5

In [27]:
# 벡터에 논리연산 적용하기
# <, <=, >, >=, ==, !=< |, &

d <- c(1,2,3,4,5,6,7,8,9,10)
d >= 5
d[d>5]
sum(d > 5)    # 5보나 큰 놈의 갯수
sum(d[d > 5]) # 40 
d == 5

condi <- d > 5 & d < 8 
condi # 논리값이 결과
d[condi] # 6, 7

[1] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

[1]  6  7  8  9 10

[1] 5

[1] 40

[1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE

[1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE

[1] 6 7

In [28]:
sum(d > 5)

[1] 5

##### R의 데이터유형과 구조

###### 1. R에서의 자료구조
>* Vector : 벡터는 R에서 가장 기본이 되는 자료구조
 - `1차원의 선형구조`형태
 - 동일한 자료형의 데이터만 저장할 수 있다.
* Matrix :  동일한 자료형을 갖는 `2차원의 배열구조`
 - 행과 열의 2차원 배열구조의 객체
 - 동일타입의 데이터만 저장가능
 - 행렬함수 : matrix(), rbind(), cbind()
 - 행렬처리함수 : apply()
* Array : 동일한 자료형을 갖는 `다차원의 배열구조`
 - 행,열,면의 3차원 배열형태의 객체
 - 행렬구조와 동일하게 index를 사용
 - 배열생성함수 : array()
* List : 성격이 다은 객체로 생성
 - `키와 값이 한쌍`으로 저장
 - 파이썬의 `dict`자료형과 유사하다.
 - key를 통해서 값에 접근할 수 있다.
 - 생성함수 : list()
 - 처리함수 : unlist(), lapply(), sapply()
* DataFrame : R에서 가장 많이 사용하는 자료구조중 하나
 - RDBMS의 테이블과 유사
 - 컬럼단위로 서로 다른 형태의 데이터를 저장가능
 - 생성함수 : data.frame(), read.table(), read.csv()
 - 처리함수 : str(), ncol(), nrow(), apply(), summary(), subset()...

###### 1) Matrix(행렬)

벡터는 원소를 단순히 1차원의 요소로 열거해 놓은 것 뿐이지만 실제 데이터는 행과 열로 이루어진 표형식을 따르는 것이 많다. 이러한 데이터 형식을 R에서는 `행렬 Matrix`라고 하고, 표형식의 데이터에 대한 분석함수를 이용하기 위해서는 사전에 `행렬화` 시킬 필요가 있다. 

행렬은 `matrix() 함수`를 이용해 바탕이 되는 vector에 행의 수 혹은 열의 수에 대한 정보를 추가함으로써 만들 수 있다. 
>행렬자료구조는 동일한 자료형을 갖는 2차원배열구조 이다.

###### Matrix의 특징

>* 행과 열의 2차원 배열구조의 객체를 생성
* 동일한 타입의 데이터만 저장이 가능
* 행렬생성함수 : `matrix(), rbind(), cbind()`
* 행렬처리함수 : `apply()`

###### matrix() 함수

>* 문법 : matrix(data=NA, nrow=1, ncol=1, byrow=F, dimnames=NULL)
>>* data : 행렬의 데이터
>>* nrow : 행의 갯수
>>* ncol : 열의 갯수
>>* byrow: 행기준 또는 열기준으로 우선여부
>>* dimnames: 차원지정

In [1]:
# 5~60까지 5씩 증가하는 정수형 벡터 작성
v <- seq(5, 60, by=5)
v

[1]  5 10 15 20 25 30 35 40 45 50 55 60

In [2]:
# 1. matrix()
# 1차원의 벡터를 행렬로 변환
matrix(v, ncol=4)

m <- matrix(c(1:5)) # 열기준으로 행렬객체를 생성
m

m1 <- matrix(c(1:10), nrow=2) # 행기준으로
m1

[,1] [,2] [,3] [,4]
[1,]  5   20   35   50  
[2,] 10   25   40   55  
[3,] 15   30   45   60

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [3]:
# 2. rbind() : 행으로 합침, cbind() : 열로 합침
v1 <- c(1,2,3)
v2 <- c(4,5,6)
v3 <- c(7,8,9)

# 행결합
mat1 <- rbind(v1, v2, v3)
mat1

# 열결합
mat2 <- cbind(v1, v2, v3)
mat2

# 행렬데이터의 컬럼에 이름을 부여
colnames(mat1) <- c('1st', '2nd', '3rd')
mat1

[,1] [,2] [,3]
v1 1    2    3   
v2 4    5    6   
v3 7    8    9

v1 v2 v3
[1,] 1  4  7 
[2,] 2  5  8 
[3,] 3  6  9

1st 2nd 3rd
v1 1   2   3  
v2 4   5   6  
v3 7   8   9

In [4]:
# 3. apply() : 행렬객체의 처리함수
# apply(data, margin(행=1, 열=2), 함수...)
length(mat1)
apply(mat1, 1, sum)
apply(mat1, 2, sum)
apply(mat1, 1, max)
apply(mat1, 2, min)

[1] 9

v1 v2 v3 
 6 15 24

1st 2nd 3rd 
 12  15  18

v1 v2 v3 
 3  6  9

1st 2nd 3rd 
  1   2   3

###### 2) Array(배열)

행렬을 다차원으로 확장한 것. 행렬은 2차원이지만 배열은 필요에 따라서 3차원이상으로도 확장이 가능한 `동일한 자료형을 갖는 다차원 배열구조`이다.

###### Array의 특징
>* 행,열,면의 3차원형태의 객체
* 행렬구조와 동일하게 Index로 접근
* 생성함수 : `array()`

In [7]:
# 1. array()
array(1:12, dim=c(3,4)) # 3행4열의 2차원배열
x <- array(1:12, dim=c(3,2))
x

# 배열의 접근방법
x[1,1]
x[3,2]

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] 1

[1] 6

In [8]:
# 2. dim() : 배열의 차원을 확인
dim(x)

[1] 3 2

###### 3) List(리스트)

리스트는 벡터나 행렬을 한꺼번에 취급할 수 있는 형태이다. 복수의 관련된 벡터나 행렬을 하나의 리스트에 보관할 수 있으며 `함수 list()`를 이용하여 생성한다. 함수의 인수 값은 리스트에 포함되는 벡터나 행렬을 지정하거나, 데이터의 참조용이름을 부여하여 사용할 수도 있다.

>리스트(List)는 성격이 다른 자료구조(벡터, 행렬, 리스트, 데이터프레임등)를 객체로 생성할 수 있다.

###### List의 특징

>* Key와 Value를 한쌍으로 저장된다.
* Python의 dict와 유사한 자료형이다.
* 접근방법은 key를 통해서 value에 접근할 수 있다.
* 생성함수 : `list()`
* 처리함수 : `unlist(), lapply(), sapply()

In [9]:
# 1. list()

myvector <- rep(c(3,2,1), 3) # 3,2,1을 3번 반복하는 벡터를 생성
myvector

[1] 3 2 1 3 2 1 3 2 1

In [10]:
mymatrix <- matrix(1:12, ncol=4) # 3x4행렬
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [11]:
# myvector와 mymatrix를 요소로 갖는 list생성
mylist <- list(dataA=myvector, dataB=mymatrix)
mylist
mylist$dataB

$dataA
[1] 3 2 1 3 2 1 3 2 1

$dataB
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [ ]:
# 리스트자료
member <- list(name="홍길동", address="인천", tel="010-9999-8888", pay=3600)
member
member$name

# 리스트조작
member$tel
member[1:3]

# 리스트에 새로운 데이터를 추가 & 수정
member$birthday <- '2020-05-01'
member$name <- '소향'
member

# R

###### 4) Dataframe(데이터프레임)

데이터프레임은 `다양한 자료형으로 구성된 2차원형태의 데이터구조`이다. 행렬과 데이터프레임은 2차원형태는 동일하지만 다른점은 행렬은 동일한 자료형만 가능하지만 `데이터프레임은 서로 다른 자료형이라도 상관 없다.`

>* 데이터프레임은 R에서 데이터분석을 수행할 때 가장 빈번히 사용되는 형식이다. 외부로 부터 R에 데이터를 불러올 때 사용하는 함수들은 불러들인 데이터를 모두 데이터프레임으로 변환시키기 때문이다. 데이터프레임은 `리스트이 한 종류`로 리스트에 포함된 모든 값이 길이가 같은 벡터일 때, 혹은 행의 수, 열의 수가 같은 행렬에 한해서 그 리스트를 `함수 data.frame()`를 이용해 데이터프레임으로 변환시 킬 수 있다.
* 데이터프레임은 행렬의 집합으로써 생성할 수도 있지만, 많은 경우 벡터의 집합으로 사용된다. 같은 길이의 벡터의 집합인 데이터프레임은 각각의 벡터를 열 원소로 간주하는 표형식의 데이터로 생각할 수가 있어서 행단위, 열단위의 데이터의 추가, 삭제, 추출등의 조작을 할 수 있다. 또한 데이터프레임을 작성할 때 각 열과 행에는 `행의 이름`, `열의 이름`이 자동으로 부여된다. 열의 이름은 리스트의 참조용이름이 사용되며 행의 이름은 `함수 rownames()`, 열의 이름은 `함수 colnamas()`로 확인할 수 있으며 자유롭게 변경할 수 있다.

###### Dataframe의 특징
>* 데이터베이스의 테이블구조와 유사
* 컬럼단위로 서로 다른 데이터자료형의 저장이 가능
* 리스트와 벡터의 혼합형으로 컬럼은 리스트, 컬럼내의 데이터는 벡터자료 구조이다.
* 생성함수 : `data.frame()`, `read.table()`, `read.csv()`
* 처리함수 : `str()`, `ncol()`, `nrow()`, `apply()`, `summary()`, `subset()`등
* 생성방법 : `Vector`, `matrix`, `파일(txt, xls, csv)`을 이용해서 생성

In [12]:
# 1. data.frame()
v1 <- 1:5
v2 <- 6:10
v1
v2
mylist <- list(dataA=v1, dataB=v2)
mylist

# 데이터프레임생성
data.frame(mylist)

[1] 1 2 3 4 5

[1]  6  7  8  9 10

$dataA
[1] 1 2 3 4 5

$dataB
[1]  6  7  8  9 10

dataA dataB
1 1      6   
2 2      7   
3 3      8   
4 4      9   
5 5     10

In [13]:
# 행, 열의 이름을 확인
mydf <- data.frame(mylist)

rownames(mydf) # 행이름을 아직 부여하지 않았기 때문에 순번으로 출력
colnames(mydf)

[1] "1" "2" "3" "4" "5"

[1] "dataA" "dataB"

In [14]:
# 2. data.frame() : 다양한 자료형으로 구성된 df
no <- c(1,2,3,4)
name <- c('사과', '바나나', '복숭아', '딸기')
prices <- c(500, 200, 300, 100)
qty <- c(5,2,7,9)

# 상기의 벡터들을 데이터프레임으로 생성 
# 다양한 자료형을 모아서 구성된 행력
fruit <- data.frame(No=no, Name=name, Price=prices, QTY=qty)
fruit

# 데이터프레임의 조작
fruit[1,] # 1행의 모든 열
fruit[,2] # 모든행의 2번열
fruit[,-2] # 모든행의 -2번열부터 끝까지

No Name   Price QTY
1 1  사과   500   5  
2 2  바나나 200   2  
3 3  복숭아 300   7  
4 4  딸기   100   9

No Name Price QTY
1 1  사과 500   5

[1] 사과   바나나 복숭아 딸기  
Levels: 딸기 바나나 복숭아 사과

No Price QTY
1 1  500   5  
2 2  200   2  
3 3  300   7  
4 4  100   9

In [15]:
# 3. str()
str(fruit)

'data.frame':	4 obs. of  4 variables:
 $ No   : num  1 2 3 4
 $ Name : Factor w/ 4 levels "딸기","바나나",..: 4 2 3 1
 $ Price: num  500 200 300 100
 $ QTY  : num  5 2 7 9


In [16]:
# 4. summary() : 기초통계량정보
summary(fruit)

       No           Name       Price          QTY      
 Min.   :1.00   딸기  :1   Min.   :100   Min.   :2.00  
 1st Qu.:1.75   바나나:1   1st Qu.:175   1st Qu.:4.25  
 Median :2.50   복숭아:1   Median :250   Median :6.00  
 Mean   :2.50   사과  :1   Mean   :275   Mean   :5.75  
 3rd Qu.:3.25              3rd Qu.:350   3rd Qu.:7.50  
 Max.   :4.00              Max.   :500   Max.   :9.00  

In [17]:
# 5. apply()
apply(fruit[,c(3,4)], 2, sum)

Price   QTY 
 1100    23

In [18]:
# 6. subset()
subset(fruit, Price>300)

No Name Price QTY
1 1  사과 500   5

In [19]:
# 7. read.csv()
read.csv('../data/input.csv', header = T)

Supplier.Name Invoice.Number Part.Number Cost Purchase.Date
1  A             001-1001       2341        500  2014-01-20   
2  A             001-1001       2341        500  2014-01-20   
3  A             001-1001       2342        750  2014-01-20   
4  A             001-1001       2342        750  2014-01-20   
5  B             50-9501        7009        250  2018-01-30   
6  B             50-9501        7009        250  2018-01-30   
7  B             50-9501        6650        125  2018-02-03   
8  B             50-9501        6650         12  2018-02-03   
9  C             920-4803       3321        615  2017-02-03   
10 C             920-4804       3321        615  2017-02-10   
11 C             920-4805       3321        615  2017-02-17   
12 C             920-4806       3321        615  2014-01-22

###### factor와 level

>* 벡터의 특수한 형태로 설문조사의 선택문항등 카테고리를 저장할 수 있는 벡터인 `factor`라는 형태가 있다. factor는 벡터를 기본으로 하여 `함수 factor()`를 이용하여 작성할 수 있다.
* factor()함수에서는 그 기본이 되는 `벡터와 levels`인수에 의해 factor의 레벨(혹은 이름)을 지정한다. level은 factor에 포함된 카테고리의 목록이라 할 수 있다. 
* factor와 vector의 내용을 R에서 출력해 보면 `factor는 벡터에 레벨정보를 추가`한 것임을 알 수 있다.
* R에서는 이 레벨정보를 이용해 카테고리별 단순집계나 그래프를 그리기때문에 카테고리변수는 가능한 벡터가 아닌 `factor로 변환`해 놓는 것이 좋다.
* factor와 벡터는 외형상 큰 차이는 없어 보이지만 R의 내부에서는 매우 다른 형태로 취급한다.
* 벡터를 숫자로 변환하는 함수 `as.numeric()`함수를 이용하면 factor는 `level의 순서에 따라 그 값이 존재`하지만, 문자형벡터는 그렇지가 않다.

In [20]:
xv <- c("A","C","B", "A", "A", "C","B")
xv

x <- factor(xv, levels=c("A", "B", "C"))
x

# 벡터 vs factor
as.numeric(xv)
as.numeric(x)

[1] "A" "C" "B" "A" "A" "C" "B"

[1] A C B A A C B
Levels: A B C

Warning message in eval(expr, envir, enclos):
"강제형변환에 의해 생성된 NA 입니다"

[1] NA NA NA NA NA NA NA

[1] 1 3 2 1 1 3 2

In [21]:
# factor(x, levels, ordered)
# x : factor로 변환할 vector데이터
# levels : 입력한 x의 데이터를 범주형으로 정의한 벡터자료형, 범주의 순서도 정의 가능
# ordered : 서열형 데이터인 경우 TRUE로 설정(기본값은 FALSE, 명목형)

# factor로 변환할 vector
v_character <- c("사과", "복숭아","사과", "오렌지","사과", "오렌지","복숭아")
v_character
v_factor <- factor(v_character)
v_factor
print(v_factor)

# ordered
v_factor <- factor(v_character, ordered=T)
print(v_factor)

v_factor <- factor(v_character, levels=c('사과', '복숭아'), ordered=T)
print(v_factor)

v_factor <- factor(v_character, levels=c('사과', '복숭아'))
print(v_factor)

[1] "사과"   "복숭아" "사과"   "오렌지" "사과"   "오렌지" "복숭아"

[1] 사과   복숭아 사과   오렌지 사과   오렌지 복숭아
Levels: 복숭아 사과 오렌지

[1] 사과   복숭아 사과   오렌지 사과   오렌지 복숭아
Levels: 복숭아 사과 오렌지
[1] 사과   복숭아 사과   오렌지 사과   오렌지 복숭아
Levels: 복숭아 < 사과 < 오렌지
[1] 사과   복숭아 사과   <NA>   사과   <NA>   복숭아
Levels: 사과 < 복숭아
[1] 사과   복숭아 사과   <NA>   사과   <NA>   복숭아
Levels: 사과 복숭아
